### ISSUE TITLE
Can't connect with Android devices

### ISSUE THREAD

**Issue by cordechasse** [freshplanet/ANE-Facebook#101]
Hi,

I'm trying to connect on a few Android devices and I'm not able to connect to facebook.
When turning on the log, I get: 

[Facebook] INFO - InitFunction, session={Session state:CREATED, token:{AccessToken token:ACCESS_TOKEN_REMOVED permissions:[]}, appId:570287986354141}

My as3 code:
_facebookConnect = Facebook.getInstance();
_facebookConnect.logEnabled = true;
_facebookConnect.init(ConfigManager.getConstant("facebook-id"));
_facebookConnect.openSessionWithReadPermissions(["read_stream", "email"], _onSessionOpened);

private function _onSessionOpened(success:Boolean, userCancelled:Boolean, error:String = null) : void {
trace(this, "_onSessionOpened", success, userCancelled, error);
}

I've created the facebook app following the guidelines found on :
http://afterisk.wordpress.com/2013/02/26/first-free-facebook-single-sign-on-sso-adobe-air-native-extension-for-android/

![image](https://f.cloud.github.com/assets/1674693/1419062/27d63936-3fc3-11e3-85bd-356207e68d09.png)

I've set the manifestAdditions in the application-descriptor.xml as described in the documentation.

Is there something I forgot?

BTW: the ANE works perfectly on iOS.

**Comment by AdamFP** [comment]
deprecated
