### ISSUE TITLE
Ane-Facebook Working Example (Read/Publish)

### ISSUE THREAD

**Issue by messi89** [freshplanet/ANE-Facebook#103]
Hello

After the last commit from our friend @ataugeron I make a new example to help you when you are going to use the ANE-Facebook from freshplanet

Download the example from the git:
https://github.com/messi89/OverGenANE

Screens:
http://imageshack.us/scaled/landing/22/n544.png
http://img33.imageshack.us/img33/9012/k6oe.png

**Comment by daksamedia** [comment]
Hi guys!
Have u guys ever using "apprequests" dialog properly?

If yes, would you show me how to use it well. Working sample I mean.

Thank u guys.

Regards.

**Comment by AdamFP** [comment]
deprecated
