### ISSUE TITLE
Call init() and get error #1009

### ISSUE THREAD

**Issue by narino** [freshplanet/ANE-Facebook#109]
please help me.

i want to use this ane. but it's stuck in _fb.init(APP_ID);
i had followed the example from https://github.com/messi89/OverGenANE/blob/master/src/overgen/android/OverGenANE.as
all setting in application.xml is same with the readme.
but i cannot get status _fb.isSessionOpen. when i tried to use try catch

try
{
    _fb.init(APP_ID);
}
catch(e:Error)
{
    tt.appendText("error : " + e.message + "\n\n");
}

it's show "Error : #1009"

can anybody help me? because i want use the publishInstall() for install tracker.

**Comment by AdamFP** [comment]
deprecated
