### ISSUE TITLE
Erreur avec le dernier ANE

### ISSUE THREAD

**Issue by akabeb** [freshplanet/ANE-Facebook#111]
Hello,

il y a un soucis avec le dernier ANE commité, il ne fonctionne pas, je dois utiliser une ancienne version ou le facebook connect sous Android ne fonctionne pas.
Savez vous quand vous metterez un ANE valide avec le facebook connect android fonctionnel?

Merci,
Bertrand

**Comment by AdamFP** [comment]
deprecated
