### ISSUE TITLE
AppEvent

### ISSUE THREAD

**Issue by ZogZogZog** [freshplanet/ANE-Facebook#120]
Bonjour,

Tout d'abord merci pour ce module ! 

Est-il prévu d'ajouter la gestion des AppEvents ? https://developers.facebook.com/docs/ios/app-events/

Dans le cas contraire, quelle solution préconisez-vous pour le tracking  ?

**Comment by PavelSyr** [comment]
Hi everyone,

+1

This is great feature. 
Do you have any plans to implement FBAppEvents?

thx a lot
