### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by kerike** [freshplanet/ANE-Facebook#140]
I've written several applications in andoid using this ane and everything was working fine. I had some complaints about facebook login not working, but there were a very small number, and I didn't take them into consideration.

Well last week we bought a new phone, a Samsung Galaxy s3 with android 4.3.3. I have a Samsung Galaxy s3 also, on which I've tested all my apps. Android version 4.3.

When I try to login on the new phone, the login process does not finish. What I am seeing is that it tries to login over and over again. I've deleted the facebook app and tried to login without SSO, and the same result: the login page pops back up and says you have to be logged in. I type in my email and pass, login and the same page pops back up.

The same app works fine on my phone, my coworkers phone and my bosses tablet.

What could be the problem? Can anyone give me an idea where to look for problems?

I've tried building the app with air 3.9 and 4.0, no clue. I've downloaded the songpop app, and it works on all devices. The OverGen tutorial doesn't work on the new phone only on the old one.

Thanks.

**Comment by idlebishop** [comment]
Another comment saying Mtilhan's fix worked. One note though: make sure to close the last two "<activity" tags with the "/>" characters.

**Comment by UmberFunk** [comment]
@kerike  Thanks A LOT!!! Your solution works perfectly.
Spent A LOT of time trying to make it work before finding your suggestion.
This ANE it has so many bugs and it's very hard to build it from working pieces spread around the web. I hope this piece was last! :) Big thanks to Freshplanet anyway of course.
