### ISSUE TITLE
Inviting friends via 'apprequests' dialog

### ISSUE THREAD

**Issue by mateo-kozomara** [freshplanet/ANE-Facebook#141]
I am having trouble sending invitations to my Facebook app with the dialog method.

This is how i am trying to send the invitation:

_facebook.dialog('apprequests',{"title":"AppTitle","message":"Some message"}, onInviteDialogFinished, true);

before that i got the permissions like this:

First i got the read permissions:
 _facebook.openSessionWithReadPermissions([], onSessionOpenResult);
then publish permissions:
_facebook.openSessionWithPublishPermissions(["publish_actions","read_friendlists","read_stream"], onOpenedPublishSessionAndShare);

Sharing with the dialog method works fine, login works fine, but inviting doesn't for some reason.

The dialog DOES get displayed, and i am able to select friends and send an invitation, but the invitation doesn't appear in any of my friends feed.

**Comment by daksamedia** [comment]
Hi @mateo-kozomara,
I got an issue when I tried AppsRequests.
The dialog won't appeared.
And I have some permission that might be required, such as :
"Friend list, publish, public_profile, email, etc"
So, could you tell me how to make a apprequests in a proper way.
