### ISSUE TITLE
Error: Duplicate platform iPhone-ARM found for extension

### ISSUE THREAD

**Issue by idlework** [freshplanet/ANE-Facebook#16]
When i want to test the application with the desktop simulator i get the this error: Duplicate platform iPhone-ARM found for extension com.freshplanet.AirFacebook

I am trying to debug the Android version on my desktop.

It works perfect when i debug it on a Android phone.

compiling happens on a macbook 17 inch, osX 10.8, fdt builder 5.5
tested on nexus s, nexus one, google nexus tablet

**Comment by mumeka** [comment]
Same error while compiling at Windows Animate CC while simulating Android Device. Working perfect at physical device. Do you know any solution? There is only one <platform name="iPhone-ARM"> at extension.xml
