### ISSUE TITLE
Upgrade for Graph 2.0 question

### ISSUE THREAD

**Issue by kerike** [freshplanet/ANE-Facebook#167]
The upgrade to Graph 2.0 for mobile devices is getting closer. I saw that on ios the sdk version is 3.16.2 which contains graph 2.0. But on android it is still 3.6.

Are you guys planning a new update? Or did I see something incorrect?

I am really satisfied with this ane, your work is great.

Thanks guys.

**Comment by qwpking** [comment]
Ane latest update file, the request is still https://m.facebook.com/v1.0 -_-\\

**Comment by kerike** [comment]
Hi qwpking,

the new ane uses v2.0. I have updated my apps, and I saw in facebook that the new logins are with 2.0. So use the new ane, it should work.

Have a great day.

**Comment by qwpking** [comment]
Hi kerike，
  Thanks for your help！\-_-/ thank!
