### ISSUE TITLE
Login Dialog Stuck on Android

### ISSUE THREAD

**Issue by mtilhan** [freshplanet/ANE-Facebook#170]
There is a problem effected all android devices. If user dont have Facebook native app and try to login on webwiew dialog stuck on the permission screen. Even user close the screen its appears again and not go away. 

Then i figured out problem only show if user change oriantation on webview dialog. Because if i dont change the oriantation its works fine on my device. But some devices changes oriantation automaticly and it doesnt works.

So i searched it and find this is a android webview bug. If you dont configure your oriantation settings then activity recreated on oriantation change. But i dont know why its not writed to here. I guess its effect to newly created app because android api changes.

Solution:
If you changed config lines in Main-app.xml and added android:configChanges="keyboardHidden|orientation|screenSize" . problem solved. 

Uses:
< activity android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation|screenSize"/>
< activity android:name="com.freshplanet.ane.AirFacebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:configChanges="keyboardHidden|orientation|screenSize"></activity>
< activity android:name="com.freshplanet.ane.AirFacebook.DialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:configChanges="keyboardHidden|orientation|screenSize"></activity>

 I tested some devices and works. Anybody confirm that bug and test it? If thats true then you guys need to change installation text.

**Comment by UmberFunk** [comment]
@mtilhan This fixes the problem. 

Tested a lot of version of this ANE. I met two working versions. I have chosen version by wastedabuser. The black screen was not closing and this fixed it.

I have met this solution in different place, but thanks anyway!

**Comment by thanhthien2010** [comment]
tks @mtilhan, This fixes the problem.
@ UmberFunk I think you need logout facebook, then running app, the black screen will not appear!
