### ISSUE TITLE
iOS - isSessionOpen always false

### ISSUE THREAD

**Issue by rankorn** [freshplanet/ANE-Facebook#178]
We are using the latest version ,which uses Facebook SDK 3.17.

On iOS only, when I return to the application after login using openSessionWithReadPermissions, the property isSessionOpen is always false. 
There is no way to check if the user was logged in before he left the app.. (in order not to show a login button)

On Android it works fine. What might be the problem?

**Comment by anhtran1989** [comment]
Ya, i test on IOS lib run good, but i test on Androi, isSessionOpen = false :( haiz, please support
