### ISSUE TITLE
Crash after onBtnShareLink option

### ISSUE THREAD

**Issue by SuperpinkRibs** [freshplanet/ANE-Facebook#180]
Hi,

I'm trying to use the ANE to post a link on Fb. 

When there's a tap, FB window opens and I'm able to post my message. After the post, it come back to my application and everything crash. No message added on Fb...

I'm just calling onBtnShareLink function on Sprite Click, like this :

``` javascript
private function onBtnShareLink(e:String):void
        {
            if(Facebook.getInstance().canPresentShareDialog()) {
                trace("ok");
                Facebook.getInstance().shareLinkDialog( "http://***.com/", "***", "*** "+e, "*** "+e, "***", errorHandler );
            } else {
                Facebook.getInstance().webDialog( "feed", { 'link':"http://***.com" }, errorHandler );
            }
        }
```

**Comment by stiv-iv** [comment]
I have the same trouble, but I found the reason. I use Chartboost ANE and Facebook ANE in one app. And they have conflict with name of function "init": https://github.com/ChartBoost/air/issues/2
No chartboost — no crash.

**Comment by SuperpinkRibs** [comment]
Pour cause de Spam, ces adresses n’existent plus.
Merci de nous faire suivre votre demande directement via l’adresse info de votre ville, se trouvant sur notre site internet.


Merci,


La production
