### ISSUE TITLE
x86 Android and 64Bit IOS Compatibility?

### ISSUE THREAD

**Issue by hybridmindset** [freshplanet/ANE-Facebook#183]
Will you be adding support for x86 devices and 64 bit IOS support to this ANE soon?

**Comment by kerike** [comment]
Hi guys,

So with this new change in iOS requiring 64 bit support, we need all our anes rebuilt?
I have 5 anes...so we need to wait to all of them to be rebuilt?

Thanks.

**Comment by PavelSyr** [comment]
Hi everyone!
We have the same problem.
Have you info about next build date with 64 bit support?
Thanks.

**Comment by neuronix** [comment]
The latest AIR 16 SDK rejects invalid ANEs and this one is not concerned when I compile my app, so I guess it's iOS 64bit-ready, even if we can't be sure by reading the commits.

**Comment by kerike** [comment]
Hi neuronix,

If you have a successful commit to ios, can you leave a feedback please? I have to do an update in a couple of days, and it would help a lot.

Thanks.
