### ISSUE TITLE
Crash on android with new ane

### ISSUE THREAD

**Issue by kerike** [freshplanet/ANE-Facebook#188]
Hi guys,

and as always, thanks for the great work.

But I have a small problem with the new ane. I have an application ready to be updated, and today I have downloaded the new ane, and the app crashes. If I put back the old ane all is ok. I am running the app on a samsung galaxy s3, android version 4.3 with the new air 16 sdk.

I am using "catlog" to catch the exception, and I am getting the following error:
java.lang.RuntimeException: Unable to start activity ComponentInfo{......../com.freshplanet.ane.AirFacebook.LoginActivity}:
java.lang.NullPointerException: Argument 'applicationId' cannot be null

Am i doing something wrong? Do we have to pass the app id in a different way?
I am using:

_facebook.init(FACEBOOK_APP_ID);

and then:

_facebook.openSessionWithReadPermissions(["email"], handler_openSessionWithPermissions);

Thanks in advance for your help.

**Comment by kerike** [comment]
Hi guys,

did someone have a successful login on android with the new ane? Or am I doing something wrong?

Tanks.

**Comment by morgenshtern** [comment]
Have the same problem with latest ane - crash after openSessionWithReadPermissions/openSessionWithPublishPermissions

But get crash, if i had successful login before. So, deleting com.facebook.SharedPreferencesTokenCachingStrategy.DEFAULT_KEY.xml and com.facebook.AuthorizationClient.WebViewAuthHandler.TOKEN_STORE_KEY.xml (in /data/data/app_name/shared_prefs) helps. I can login again, get friends etc. but get crash after next launch app/login.

And thanks for the great work.

**Comment by idlebishop** [comment]
Running into this as well.

Supposedly this is the answer to the applicationid being null, but I have yet to actually get it working: http://stackoverflow.com/questions/16156856/android-facebook-applicationid-cannot-be-null

**Comment by mparrett** [comment]
Tried the possible fix related to applicationId, no luck here.
