### ISSUE TITLE
ios session reauthorization with publish permission doesn`t work 

### ISSUE THREAD

**Issue by BregoXX** [freshplanet/ANE-Facebook#189]
During session reauthorization with publish permission i see in log - 'Trying to reauthorize session with ...' and then 'Session opened with ...' instead of 'Session reauthorized with permissions...'

**Comment by hazardsoft** [comment]
+1

**Comment by mickjagger** [comment]
+1

**Comment by vzhalezny** [comment]
+1

**Comment by samoiloff** [comment]
+1

**Comment by j3k0** [comment]
+1

**Comment by j3k0** [comment]
Anyone found fix for this?

**Comment by j3k0** [comment]
Fixed: was a misconfiguration in the -app.xml file (see project's main page for doc)
