### ISSUE TITLE
DialogActivity in android application descriptor should be WebDialogActivity?

### ISSUE THREAD

**Issue by loonychewy** [freshplanet/ANE-Facebook#190]
In the latest version of the ANE, for Android, there's no more DialogActivity activity, but a WebDialogActivity activity. So shouldn't the application descriptor be updated from
`<activity android:name="com.freshplanet.ane.AirFacebook.DialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"></activity>`
to
`<activity android:name="com.freshplanet.ane.AirFacebook.WebDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:configChanges="orientation"></activity>`
(I've also added in the `android:configChanges` field to prevent the activity from changing orientation when the device orientation change)

I was trying to show an 'apprequests' dialog, but it wasn't showing up on Android (shows up on iOS). Modifying the activity name solves the problem for me.

**Comment by morgenshtern** [comment]
Big thanks! I've spend two days find why apprequests not working :)
