### ISSUE TITLE
Application has stopped / java.lang.RuntimeException: Unable to resume activity.

### ISSUE THREAD

**Issue by axldns** [freshplanet/ANE-Facebook#197]
Hello,
I'm aware that this issue is already arisen in few other threads. App stops right after calling `openSessionWithReadPermissions`
For obvious reasons text bellow and attached [log file](https://drive.google.com/file/d/0B3Z-tgto3OaicDJzaUNmd1k1TGs/view?usp=sharing) have values replaced as follows:
<i>MyNumericAppId</i> - my app id ('0234XXXXXXXXX')
<i>air.com.mydomain.myapp.debug</i> - my app package (air.com.recxxxxx.xxxxx.debug)
1. I've configured manifest and extension sections in application.xml according to readme and howto:<br>

```
    <android>
        <manifestAdditions><![CDATA[
            <manifest android:installLocation="auto">
[...]
                 <uses-permission android:name="android.permission.INTERNET"/>
                 <application>
                    <activity android:name="com.facebook.LoginActivity"/>
                    <activity android:name="com.freshplanet.ane.AirFacebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.ShareDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.ShareOGActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>
                    <activity android:name="com.freshplanet.ane.AirFacebook.WebDialogActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>      
               </application>
            </manifest> 
        ]]></manifestAdditions>
    </android>
[...]
<extensions>
        <extensionID>com.freshplanet.AirFacebook</extensionID>
</extensions>
```
1. I've configured app facebook side (generated hashes based on certificate and password I've created earlier).
   ![fb](https://cloud.githubusercontent.com/assets/5039892/6632586/adb9b760-c930-11e4-8eb4-57bc728baa39.jpg)
2. I've included both ane and swc to the package
3. I'm caling methods in order:<br>

```
trace("ANE RUN", Facebook.isSupported);
Facebook.getInstance().init(MyNumericAppId,false);
Facebook.getInstance().logEnabled = true;
trace('Facebook.getInstance().isSessionOpen', Facebook.getInstance().isSessionOpen);
Facebook.getInstance().closeSessionAndClearTokenInformation();
Facebook.getInstance().openSessionWithReadPermissions(["public_profile", "user_friends"],aneSessionResult);
```

Method aneSessionResult is never executed. Application stops immediately after calling `openSessionWithReadPermissions`  Delaying or triggering this method on user input event - gives the very same result.
<br>
I'm attaching full info-level, not filtered [log file](https://drive.google.com/file/d/0B3Z-tgto3OaicDJzaUNmd1k1TGs/view?usp=sharing), captured from start of the app till the crash occurrence  (replaced app id and package).

**Comment by mparrett** [comment]
We're experiencing the same, with similar Facebook settings.

**Comment by st3veV** [comment]
Same problem here. I debugged the whole thing for a while and it seems that there is a problem with resources (some of the resources required for the login dialog to open are null).
