### ISSUE TITLE
Can auto-login after running the app? 

### ISSUE THREAD

**Issue by leejuntaek** [freshplanet/ANE-Facebook#198]
1. app login
   2.app exit
2. app play - init check -> disconnect session 

Just one thing I'd like to feature
If you run the app and when I want to auto-login to the login information.

Currently, the init () function, you can call it tells me that the session is closed.

I want to login each time you run the app without it.

Can auto-login after running the app? Thank you

**Comment by wastedabuser** [comment]
Please correct me if i misunderstood your question ...
I am doing this by setting a flag in a storage. After running the app it checks for the flag and if it is true it initiates a Facebook connect and gets a new session. If the flag is not available the app waits for user command (a press of a button).
This setup behaves exactly as a auto-login.

**Comment by PavelSyr** [comment]
Hi guys!

for example my app works on iPod4G

1) app is started at first time.
2) app waits to user command to login
3) User press to login button
4) ANE redirects app into safari web browser
5) Application may be killed by system
6) FB login page redirects to app by URLScheme (e.g. fbAPP_ID://authorize/#state...)
7) App restarts with InvokeEvent.arguments. There are a lot of url arguments, there is access_token argument
8)And isSessionOpen is false, accessToken is null

i tried to call method _context.call("handleOpenURL", url), without any results

has ANE any solution for this case?

thx a lot!
