### ISSUE TITLE
Latest updates is not compiling

### ISSUE THREAD

**Issue by algotechnologies** [freshplanet/ANE-Facebook#199]
Error: The extension com.freshplanet.AirFacebook has either a namespace version or library.swf with a version that is incompatible with the applications namespace or root SWF.
![error](https://cloud.githubusercontent.com/assets/10543630/6676933/69bb7574-cc4d-11e4-8895-b80417e67677.png)

**Comment by wastedabuser** [comment]
Your project is being compiled with target AIR version lower than the ANE. Configure you project to be compiled with at least -swf-version=25
The latest released (not beta) AIR SDK is 16.0.0 (compiles to swf version 27)
