### ISSUE TITLE
Crash app Android

### ISSUE THREAD

**Issue by anhtran1989** [freshplanet/ANE-Facebook#203]
Hi all friends, i create project test Facebook. On IOS, project is good, but on Android, app crash. Pls help me

**Comment by promatik** [comment]
I'm having the same problem, here is the Android log:

```
W/System.err(6727):
java.lang.RuntimeException: Unable to resume activity {air.my.package.name/com.facebook.LoginActivity}:
java.lang.NullPointerException
```

**Comment by caicingsian** [comment]
I have same problem!! 
I try to fix this, and i found I get exception in class com.facebook.LoginActivity function onBackgroundProcessingStarted. seen like findViewById have some issue but i don't know why
so, i use try catch in onBackgroundProcessingStarted,onBackgroundProcessingStopped,onPause three position, and recompiler ,it is work for me.
anyone know why i will got this problem?

This is my ane file, but i dont have mac, so this only include android version.
https://dl.dropboxusercontent.com/u/39823405/Works/Flash/AIR%20Native%20Extensions/AirFacebook.ane

**Comment by caicingsian** [comment]
i forgot, my first issus is can not found LocalBroadcastManager, so i put android-support-v4.jar in build.xml and platform-android.xml

build.xml

==>      <copy file="../android/libs/android-support-v4.jar" todir="temp/android/"/>

platform-android.xml
<packagedDependencies>
==>        <packagedDependency>android-support-v4.jar</packagedDependency>
         .....
<packagedDependencies>

**Comment by amhofny** [comment]
check this version, it uses AIR 18.0 and compiled for both IOS and Android, it is based on @wastedabuser changes
https://github.com/amhofny/ANE-Facebook
