### ISSUE TITLE
worst ane

### ISSUE THREAD

**Issue by DamboRam** [freshplanet/ANE-Facebook#206]
Nothing is working

**Comment by wastedabuser** [comment]
Its "opensource" dude...
Try my build (for Android) https://github.com/wastedabuser/ANE-Facebook

**Comment by jacobholm** [comment]
Hello wastedabuser,

As you seem to have managed to compile the source using ant, I was hoping you could help me. When trying to compile I am using android sdk 1.9 (the example file says 1.6, is this needed?) I have also left the bin.ext argument in build.config blank, could this be the problem? I am getting these errors:

android-build:
     [echo] Using Java version 1.7.
    [javac] Compiling 123 source files to D:\Downloads\ANE-Facebook-master\ANE-F
acebook-master\build\temp\android\build
    [javac] warning: [options] bootstrap class path not set in conjunction with
-source 1.6
    [javac] D:\Downloads\ANE-Facebook-master\ANE-Facebook-master\android\src\com
\facebook\widget\WebDialog.java:218: error: cannot find symbol
    [javac]         spinner.setMessage(getContext().getString(AirFacebookExtensi
on.getResourceId("string.com_facebook_loading")));
    [javac]                                                   ^
    [javac]   symbol:   variable AirFacebookExtension
    [javac]   location: class WebDialog
    [javac] D:\Downloads\ANE-Facebook-master\ANE-Facebook-master\android\src\com
\facebook\widget\WebDialog.java:362: error: cannot find symbol
    [javac]         Drawable crossDrawable = getContext().getResources().getDraw
able(AirFacebookExtension.getResourceId("drawable.com_facebook_close"));
    [javac]
     ^
    [javac]   symbol:   variable AirFacebookExtension
    [javac]   location: class WebDialog
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors
    [javac] 1 warning

Hopefully you can help, thanks in advance.

**Comment by wastedabuser** [comment]
Hi,

You should use JDK 6 instead of 7 when compiling the java source.

Regards,
--
Andrey Glavchev
Website: http://essenceworks.com
Facebook: https://www.facebook.com/andrey.glavchev

**Comment by jacobholm** [comment]
Hi, I removed my response because I solved it. Turns out I forgot the following line after implementing your resource fix:

import com.freshplanet.ane.AirFacebook.AirFacebookExtension;

Although now I am facing another problem described here: https://github.com/freshplanet/ANE-Facebook/issues/211
