### ISSUE TITLE
 Resource values warning message

### ISSUE THREAD

**Issue by 62316e** [freshplanet/ANE-Facebook#215]
Warning: Resource values-he/strings.xml has been skipped because of mismatch with supported languages information in application descriptor.
Warning: Resource values-iw/strings.xml has been skipped because of mismatch with supported languages information in application descriptor.

**Comment by stigmawall** [comment]
Did you fix it? I have the same problem here.

**Comment by hybridmindset** [comment]
I get this same error when packaging with AIR 18.0
