### ISSUE TITLE
Nothing happens when pressing connect when using sample provided

### ISSUE THREAD

**Issue by UmberFunk** [freshplanet/ANE-Facebook#218]
Hello,

I downloaded ANE and sources today. Made everything as described in installation instruction + added and filled Android platform to Facebook developers page. Added app ID and basic permissions to code.
When I press connect button - nothing happens, and no any debug traces. Tested on several devices.

I searched and downloaded other branches of ANE and one of them worked, but only with FacebookPermissionEvent added from this repository. Now it can connect and disconnect, but other buttons doesn't work.

Any help would be highly appreciated.

Thanks!

**\* UPDATE ***

App is crashing with this ANE. Downloaded mattmurton's branch ANE and so far it seems working.

**Comment by UmberFunk** [comment]
Removed everything in sample except needed for login. Same again.

**Comment by UmberFunk** [comment]
*** UPDATE ***

Just today spotted that mattmurton's branch ANE has no IOS in it. ://///

**Comment by dr-andy** [comment]
Same here it crashes on Android.

**Comment by amitpal** [comment]
its not working for me as well?
