### ISSUE TITLE
requestWithGraphPath 

### ISSUE THREAD

**Issue by anylxl** [freshplanet/ANE-Facebook#219]
I see you have written articles from https://github.com/freshplanet/ANE-Facebook, and has been concerned about your updates,

I recently updated from you, I found a few problems,

1, Facebook.getInstance () requestWithGraphPath ("/ me", null, "GET", requesetWithGraphPathHandler);
Methods requesetWithGraphPathHandler, not return parameter "data".

2, AirFacebook.ane larger file content

You can help me answer it? Thank you very much。

**Comment by UmberFunk** [comment]
Hello @anylxl,

Did you managed to make it work on Android. It's crashing when openSessionWithReadPermissions is called. Tested on two devices.

**Comment by anylxl** [comment]
Hello @UmberFunk,
in IOS 8.3 . I found "requestWithGraphPath" method can not be used. because AIR SDK15.0

**Comment by UmberFunk** [comment]
Hi @anylxl 

I think it would be better to switch to latest SDK. Latest version does support new IOS versions.

I finally found a good version of Facebook ANE. I'm going to test it with iOS this days. 
Link:
https://github.com/freshplanet/ANE-Facebook/blob/bc2a8a3a4037b8c12508ba5a70ae1eaee034ee00/bin/AirFacebook.anehttps://github.com/freshplanet/ANE-Facebook/blob/bc2a8a3a4037b8c12508ba5a70ae1eaee034ee00/bin/AirFacebook.ane
clear token before connecting.

**Comment by UmberFunk** [comment]
If it isn't copy-paste problem, there's an extra space in your code:
"/ me" 
should be 
"/me"

**Comment by anylxl** [comment]
I try now. tks

**Comment by anylxl** [comment]
hi, @UmberFunk , this link," page not found".

https://github.com/freshplanet/ANE-Facebook/blob/bc2a8a3a4037b8c12508ba5a70ae1eaee034ee00/bin/AirFacebook.anehttps://github.com/freshplanet/ANE-Facebook/blob/bc2a8a3a4037b8c12508ba5a70ae1eaee034ee00/bin/AirFacebook.ane

**Comment by UmberFunk** [comment]
Sorry, I accidently doublepasted it.

Corrected:
https://github.com/freshplanet/ANE-Facebook/blob/bc2a8a3a4037b8c12508ba5a70ae1eaee034ee00/bin/AirFacebook.ane
