### ISSUE TITLE
Auto-connect at startup without calling openSessionWithReadPermissions

### ISSUE THREAD

**Issue by UmberFunk** [freshplanet/ANE-Facebook#220]
Hello again,

After LOTS of tests I managed to to make 2 versions of ANE-Facebook work:
1. wastedabuser's version. Sadly it hasn't IOS support, but on Android after app restart the session is still open after init.
2. Commit of master by shinyamos. It supports both platforms but after restarting app, Facebook isSessionOpen is false, unlike version of wastedabuser. That's very bad because this way a user will see a black splashscreen at every app start.

Is there any way to make commit from master (2) to start with opened session?

Now I'll test versions by FreshTiti made for Songpop

**Comment by UmberFunk** [comment]
AT LAST!!!
Found a version that work as it should! Thanks to @FreshTiti !!!

**Comment by anylxl** [comment]
I want to get facebookId, but I can not get.

**Comment by UmberFunk** [comment]
@anylxl I'll try to help if you tell me more details.

**Comment by anylxl** [comment]
I want to get gamers facebook Id, I can not get, I tried many other methods.
 Example
 requestWithGraphPath ("/ me", null, "GET", requesetWithGraphPathHandler)

**Comment by deccosantos** [comment]
try this:

Facebook.getInstance().requestWithGraphPath("me",null,"GET",facebookIDRecieved1);
function facebookIDRecieved1(obj:Object):void {
var name:String = obj.name;
var id:Number = obj.id;
}
So you can display a var id in a textfield, for example textfield.text = id;

**Comment by UmberFunk** [comment]
@deccosantos You are right. "me" and not "/me"
"me"  - Data about you.
"me/friends" - Friends who are already joined your game with Facebook. You can send them game requests (send gift, request to send something etc.)
"me/invitable_friends" - Friends whom you can send game requests (invites). After joining, they jump to friends.
