### ISSUE TITLE
iOS 6 Compatibility

### ISSUE THREAD

**Issue by josaliba** [freshplanet/ANE-Facebook#223]
Hi,

I am currently looking at your updateSDK branch since I need an ANE using FB SDK 4.6.0.

However, it seems it's not working on iOS 6. Do you know if it's compatible with iOS 6? If not, is it possible for you to recompile it for iOS 6 also?

I would really appreciate it.
Thanks

**Comment by josaliba** [comment]
FYI

The error i'm getting is “<Error>: libMobileGestalt copySystemVersionDictionaryValue: Could not lookup ReleaseType from system version dictionary:.

Looking at the iOS crash report, this is what I find:

Dyld Error Message:
  Symbol not found: _NSKeyedArchiveRootObjectKey
  Referenced from: /var/mobile/Applications/B1832D79-E4E4-4678-8FC0-4A05F62E2816/TestAds.app/TestAds
  Expected in: /System/Library/Frameworks/Foundation.framework/Foundation
 in /var/mobile/Applications/B1832D79-E4E4-4678-8FC0-4A05F62E2816/TestAds.app/TestAds
  Dyld Version: 212.3

**Comment by FreshTiti** [comment]
According to Facebook documentation:
`iOS 6 is no longer supported. The FacebookSDK for iOS v4.0 requires iOS 7 or higher.`
