### ISSUE TITLE
Callbacks not called when an error occurs.

### ISSUE THREAD

**Issue by cemuzunlar** [freshplanet/ANE-Facebook#25]
Example:

After successfully logging in to Facebook, we make a bogus request for testing purposes:

``` javascript
Facebook.getInstance().requestWithGraphPath("/me/dfgdfg/", { "fields":"permissions,first_name,last_name" }, "GET", requestCallback);
```

We see the error is written to output:

[Facebook] INFO - Session closed
[Facebook] Request error: Error Domain=com.facebook.sdk Code=5 "The operation couldn’t be completed. (com.facebook.sdk error 5.)" UserInfo=0x8b2f10 {com.facebook.sdk:ParsedJSONResponseKey=

``` json
{
    body =     {
        error =         {
            code = 2500;
            message = "Unknown path components: /dfgdfg";
            type = OAuthException;
        };
    };
    code = 400;
}, com.facebook.sdk:HTTPStatusCode=400}
```

but requestCallback is not called with the error.

**Comment by AdamFP** [comment]
deprecated
