### ISSUE TITLE
no resource found @style/theme.appcompat.light

### ISSUE THREAD

**Issue by wussow-everi** [freshplanet/ANE-Facebook#256]
I've followed the integration guide on the wiki and have tried to build to Android.

I'm using Adobe AIR 27, and when I try to build my project and I get the error:

`error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light'. `

Has anyone had this problem before? I'm wondering if its a mismatch with the appcompatv7 versions bundled with AIR. Should I build the ANE with AIR 27?

**Comment by chpla** [comment]
Having a somewhat similar issue here:

> aapt tool failed:/private/var/folders/2m/wvvsjw_556x1nfb609n1rmnc0000gn/T/9d11f58e-9fb0-4d52-a61f-75c8577d4522/AirFacebook-res/values/values.xml:131: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.NoActionBar'.

> /private/var/folders/2m/wvvsjw_556x1nfb609n1rmnc0000gn/T/9d11f58e-9fb0-4d52-a61f-75c8577d4522/AirFacebook-res/values/values.xml:136: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Dialog'.

This happens when I try to use the .ane from the bin folder in my app. It keeps happening no matter what I set the `targetSdkVersion` and `minSdkVersion` to, with AIR SDK versions ranging from 24 to 27.

**Comment by wussow-everi** [comment]
So I was able to fix this. But I'm using a kind of unique setup. I'm using the myflashlabs Firebase ANEs. And those require an ANE called androidSupport-full.ane it can be found [here](https://github.com/myflashlab/common-dependencies-ANE/tree/master/androidSupport). 

Here are the steps you need to take:

1. Include the androidSupport-full.ane
2. Download this repo (ANE-Facebook)
3. Locate this file: ANE-Facebook/build/platform-android.xml
4. Comment out these 2 lines: 
 ```
<packagedDependency>cardview-v7-25.0.0.jar</packagedDependency>
<packagedDependency>customtabs-25.0.0.jar</packagedDependency>
```
5. Follow the steps to build the ANE
6. Include the new ANE-Facebook in your project

**Comment by franmocad** [comment]
@wussow-everi, could You share the ane file that you created? 
Please, it would be very helpful.
Thanks in advance
