### ISSUE TITLE
How to resolve conflicts between two ANE?

### ISSUE THREAD

**Issue by orcuncun** [freshplanet/ANE-Facebook#266]
i want to use together that Facebook ANE and admob ANE but Files in ANE conflicts,
How to resolve?
![capture](https://user-images.githubusercontent.com/29103010/46823996-5a639980-cd98-11e8-933b-34102a4251c9.JPG)

**Comment by romeoobane** [comment]
Hi, is there any solution added to this issue? Thanks!
