### ISSUE TITLE
dialog("apprequests", ...) showing "Post to Wall" dialog instead

### ISSUE THREAD

**Issue by billbaldwin** [freshplanet/ANE-Facebook#47]
I've just started doing some testing with this ANE on iOS, but I can't get the apprequests dialog to display. 

Login, get user data, get friends, get app requests all work fine, but when I try to open the apprequests dialog to send a request, I get a "Post to Wall" dialog instead. 

The parameters to

**_context.call('dialog', method, keys, values, callbackName, allowNativeUI);**

all look correct and reasonable, and method = 'apprequests.' 

After this call, I see a call to **Facebook.onStatus()** with the following in **event.level**:

**displaying facebook feed dialog : allowNativeUI - YES, canPresentNativeDialog - NO, isFeedingDialog - NO, hasNoRecipient - NO**

I have no doubt this is user error - any suggestions?

**Comment by AdamFP** [comment]
deprecated
