### ISSUE TITLE
If SDK has error message for user, please return it!

### ISSUE THREAD

**Issue by troygilbert** [freshplanet/ANE-Facebook#76]
The current logic in the ANE looks for an error matching `FBErrorLoginFailedReasonSystemDisallowedWithoutErrorValue` and dispatches `"APPLICATION_TURNED_OFF"` instead of the error message provided by the SDK (which it does for other errors). This message in particular is very useful as it's localized instructions specific to the OS version directing the user to enable the app in settings. Would love to not have to recreate this app-side since the Facebook SDK is already doing the work.

Any particular reason why this substitution was made?

**Comment by AdamFP** [comment]
deprecated
